---
# Handlers for RKE2 registry configuration

- name: Restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  when:
    - ansible_facts['services']['rke2-server.service'] is defined
    - ansible_facts['services']['rke2-server.service']['state'] == 'running'
  failed_when: false

- name: Restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  when:
    - ansible_facts['services']['rke2-agent.service'] is defined
    - ansible_facts['services']['rke2-agent.service']['state'] == 'running'
  failed_when: false
